### ISSUE TITLE
关于加入一言

### ISSUE THREAD

**Issue by cyb1010** [fluid-dev/hexo-theme-fluid#1009]
我想要给主页加入一言。

官方文档中说: 

```修改layout目录下的layout.ejs，在<span class="h2" id="subtitle">和<% if(is_post()) { %>之间插入如下代码......```

可是 layout.ejs中并没有以上代码，我试了几个地方，也不知道应该加在哪里。求助。

**Comment by LAGQWQ** [comment]
你他妈别在issues区拉屎

**Comment by xiyuvi** [comment]
你看的什么文档，首页加入一言是在_config.fluid.yml 中搜索一以下内容进行配置，fluid的配置是很灵活的，尽量不会让你修改源码实现功能
```
# 通过 API 接口作为首页副标题的内容，必须返回的是 JSON 格式，如果请求失败则按 text 字段显示，该功能必须先开启 typing 打字机功能
    # Subtitle of the homepage through the API, must be returned a JSON. If the request fails, it will be displayed in `text` value. This feature must first enable the typing animation
    api:
      enable: true

      # 请求地址
      # Request url
      url: "https://v1.hitokoto.cn/?c=k"

      # 请求方法
      # Request method
      # Available: GET | POST | PUT
      method: "GET"

      # 请求头
      # Request headers
      headers: {}

      # 从请求结果获取字符串的取值字段，最终必须是一个字符串，例如返回结果为 {"data": {"author": "fluid", "content": "An elegant theme"}}, 则取值字段为 ['data', 'content']；如果返回是列表则自动选择第一项
      # The value field of the string obtained from the response. For example, the response content is {"data": {"author": "fluid", "content": "An elegant theme"}}, the expected `keys: ['data','content']`; if the return is a list, the first item is automatically selected
      keys: ["hitokoto"]
```
