### ISSUE TITLE
自动摘要包含大量无意义的代码块行号

### ISSUE THREAD

**Issue by tauyoungsama** [fluid-dev/hexo-theme-fluid#1034]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

当启用自动摘要，且文章开头附近包含启用了行号的代码块时，自动生成的摘要会包含大量来自行号的数字。行号不包含有意义的信息，不应该被加入摘要。这个bug在生成静态文件的过程中生效，与浏览器无关。

```yml
code:
  line_number: true
index:
  auto_excerpt:
    enable: true
```

#### 复现步骤
该 Bug 复现步骤如下：
1. 在配置文件中启用自动摘要和代码块行号；
2. 在文章的开头包含较长的代码块；
3. 发布后访问博客主页，自动摘要里面全部是行号组成的数字。

参考：https://blog.tauyoung.top 中「请使用 XDG 基本目录规范！」一文下的摘要。

#### 截图

<img width="687" alt="image" src="https://github.com/fluid-dev/hexo-theme-fluid/assets/39393816/8ea80f7e-163b-46fc-84f3-94c42ea325ec">
