### ISSUE TITLE
与 hexo-generator-sitemap 配合使用时，关于页面地址不规范：/about/index.html，影响 SEO

### ISSUE THREAD

**Issue by AnzhiZhang** [fluid-dev/hexo-theme-fluid#1037]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

与 [hexo-generator-sitemap](https://github.com/hexojs/hexo-generator-sitemap) 共同配合使用时，关于页的站点地图生成了 `/about/index.html`，实际的规范网页应该是 `/about/`。由于不确定是主题的问题还是该插件的问题，故寻求帮助。
我查看了 `db.json`，个人页面的 path 也是 `about/index.html`：

```json
"path":"about/index.html"
```

**Comment by AnzhiZhang** [comment]
相关 issue：hexojs/hexo#1306

**Comment by mobeicanyue** [comment]
后缀可以去的吧，如果你不想显示 .html 
在 _config.yml
```
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks
```
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/81098819/ca7aadc9-23b6-43ec-bbec-57bb45c04ac3)
