### ISSUE TITLE
代码块被加上了紫色背景

### ISSUE THREAD

**Issue by DubheHub** [fluid-dev/hexo-theme-fluid#1049]
#### 请确认
- [ √] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ √] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

安装依赖信息：

```json
  "hexo": {
    "version": "7.0.0"
  },
  "dependencies": {
    "hexo": "^7.0.0",
    "hexo-abbrlink": "^2.2.1",
    "hexo-blog-encrypt": "^3.1.9",
    "hexo-deployer-git": "^4.0.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-fluid": "^1.9.7",
    "hexo-theme-landscape": "^1.0.0"
  }
```

所有版本一个月没变动过，最近部署后发现代码高亮区域加上了一个紫色背景块：

![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/71436398/5cad8c7f-6fb6-43fa-a1d6-af5a03f99a49)

感觉很奇怪，从来没有修改过配置文件，为什么会有这种效果？

配置：

``` yml
# 代码块的增强配置
# Enhancements to code blocks
code:
  # 是否开启复制代码的按钮
  # Enable copy code button
  copy_btn: true

  # 代码语言
  # Code language
  language:
    enable: true
    default: "TEXT"

  # 代码高亮
  # Code highlight
  highlight:
    enable: true
    # 代码块是否显示行号
    line_number: true
    # 实现高亮的库，对应下面的设置
    # Options: highlightjs | prismjs
    lib: "prismjs"
    highlightjs:
      # 在链接中挑选 style 填入
      # See: https://highlightjs.org/static/demo/
      style: "github gist"
      style_dark: "dark"
    prismjs:
      # 在下方链接页面右侧的圆形按钮挑选 style 填入，也可以直接填入 css 链接
      # See: https://prismjs.com/
      style: "default"
      style_dark: "tomorrow night"
      # 设为 true 高亮将本地静态生成（但只支持部分 prismjs 插件），设为 false 高亮将在浏览器通过 js 生成
      preprocess: false
```

无论使用highlightjs还是prismjs，问题依旧。
