### ISSUE TITLE
将首页头图高度设置为0时(`banner_img_height: 0`)，顶栏和文章列表异常

### ISSUE THREAD

**Issue by yzl3014** [fluid-dev/hexo-theme-fluid#1066]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

Chrome版本：121.0.6167.185

在配置文件中将首页的`banner_img_height`设置为0时，首页的文章列表的第一项显示在了页面最顶端，与顶栏重叠。

此时文章标题链接被顶栏覆盖，文章标题的链接无法被点击，顶栏变为透明所以也无法使用。

```yaml
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  # Path of Banner image, can be a relative path or an absolute path, the same on other pages
  banner_img: /img/default.png

  # 头图高度，屏幕百分比
  # Height ratio of banner image
  # Available: 0 - 100
  banner_img_height: 0
```

#### 复现步骤

将主题配置文件中，首页的`banner_img_height`值修改为0。代码位置如上所示。

#### 截图

> ![](https://s2.loli.net/2024/02/18/tNs6F5Th9Q2R3CY.gif)
> https://www.yuanzj.top/

移动端效果一致。

我想要这样的效果：

> ![](https://s2.loli.net/2024/02/18/6Rm1cCi2vIwrM4Y.png)
> https://u.sb/
