### ISSUE TITLE
footer 运算符写错，导致footer 统计 false 时还会显示多余信息

### ISSUE THREAD

**Issue by joebnb** [fluid-dev/hexo-theme-fluid#132]
![image](https://user-images.githubusercontent.com/1646883/72766638-b10e8300-3c2b-11ea-8c64-7e72fb4956fc.png)

```
footer:
  statistics:  # 统计网站 PV、UV，使用的是不蒜子，显示在页脚
    enable: false // 这里
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"
```
