### ISSUE TITLE
请问能否在菜单栏再加一个自定义菜单，链接到自定义页面

### ISSUE THREAD

**Issue by larva2333** [fluid-dev/hexo-theme-fluid#146]
我已经做了如下的修改，但是还是没能实现：
```
#---------------------------
# 页头
# Header
#---------------------------
navbar:
  blog_title:  # 导航栏左侧的标题，为空则按 hexo config.title 显示
  menu:  # 可自行增减，若想减去某个入口，可以将值留空，显示文本关联 languages
    home: /
    archive: /archives/
    category: /categories/
    tag: /tags/
    links: /links/
    about: /about/
    activities: /activities/
```
复制 `links.ejs` 为 `activities.ejs`

`hexo new page 'activities'`
然后将 Front-Matter 中的layout: 设为 false 。同时在同级文件夹下新建`index.html`

最后点击`activities`时中间内容显示为空，希望能访问到index.html的内容
