### ISSUE TITLE
添加独立页面空白

### ISSUE THREAD

**Issue by DefectingCat** [fluid-dev/hexo-theme-fluid#151]
hexo: 4.2.0，主题是最新的

使用`hexo new page "test"`创建新的独立页面，并且写上了内容。位置为hexo目录下的`source/test`

然后在主题配置文件中添加：
```
navbar:
  blog_title:  # 导航栏左侧的标题，为空则按 hexo config.title 显示
  menu:  # 可自行增减，若想减去某个入口，可以将值留空，显示文本关联 languages
    home: /
    archive: /archives/
    category: /categories/
    tag: /tags/
    about: /about/
    links: /links/  # 友链页，把前面#去掉即可展示
    test: /test/
```

生成之后，navbar上可以看到新增的页面按钮，点进去没有任何内容。不是404，`public`中的对应路径中的html也是没有我写的内容。

应该就是我添加的页面test.md没有成功生成。

不知是我哪里操作出了问题，试过各种方法，无解……

![Annotation 2020-02-23 175740](https://user-images.githubusercontent.com/25033493/75110185-0b08cb00-5666-11ea-860b-62e308f73eb8.png)
