### ISSUE TITLE
请问可以在不同的文章页有不同的TOC设置吗？

### ISSUE THREAD

**Issue by Harvey-W** [fluid-dev/hexo-theme-fluid#155]
https://harvey-w.github.io/2020/02/23/hello-world/
这是我的主页，由于这篇是不带header的文章，想去掉旁边的TOC，但是如果直接在config里面设置的话好像是统一被取消了，可以按需要开关诸如TOC、comment，或者非主home页的typing subtitle这些功能吗？

**Comment by 0x2E** [comment]
感谢建议。
1. 在文章 Front-matter 中设置值为 `false` 可关闭相应功能：
```yml
title: test
date: 2018-7-24 23:31:06
toc: false
comments: false
```
2. subtitle 是页面主要元素之一，暂不考虑让用户控制。
