### ISSUE TITLE
建议修改这段css代码

### ISSUE THREAD

**Issue by cooper1x** [fluid-dev/hexo-theme-fluid#173]
我在自定义css的时候，发现跟这段冲突了。
![image](https://user-images.githubusercontent.com/9080789/76462287-61bf2480-641c-11ea-80de-f33c7aea9c46.png)
这段代码貌似只是为了调整间距，如果是这样的话，为何不在h1上面加margin或者padding呢？
我想用before做这样的操作，实现标题序号功能，代码如下：
```CSS
.container-fluid h1 { counter-reset: h2counter; }
.container-fluid h2 { counter-reset: h3counter; }
.container-fluid h3 { counter-reset: h4counter; }
.container-fluid h4 { counter-reset: h5counter; }
.container-fluid h5 { counter-reset: h6counter; }
.container-fluid h2:before {
  counter-increment: h2counter;
  content: counter(h2counter) ".\0000a0\0000a0";
}
.container-fluid h3:before {
  counter-increment: h3counter;
  content: counter(h2counter) "."
            counter(h3counter) ".\0000a0\0000a0";
}
.container-fluid h4:before {
  counter-increment: h4counter;
  content: counter(h2counter) "."
            counter(h3counter) "."
            counter(h4counter) ".\0000a0\0000a0";
}
.container-fluid h5:before {
  counter-increment: h5counter;
  content: counter(h2counter) "."
            counter(h3counter) "."
            counter(h4counter) "."
            counter(h5counter) ".\0000a0\0000a0";
}
```
