### ISSUE TITLE
锚图标功能有效，但是字符无法看到

### ISSUE THREAD

**Issue by AlchemicRonin** [fluid-dev/hexo-theme-fluid#198]
### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等旧浏览器 
- [x] 本地 `hexo s` 可以复现（排除是 CDN 缓存等原因）
- [x] 清除浏览器缓存或更换浏览器仍可复现

### Bug 描述
`为文章内容中的标题添加锚图标`功能有效，但是字符无法看到

浏览器: Chrome 80.0.3987.132 64位

### 复现步骤
该 Bug 复现步骤如下：
1. ```
    anchorjs: # 为文章内容中的标题添加锚图标
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: right # icon放置的位置： left | right
    visible: always # 默认悬浮显示，可选：hover（鼠标在元素上悬浮时显示） | always（一直显示） | touch（移动端触摸显示）
    icon: "§" # 可选：§ | # | ❡ 等，留空则为默认效果
2. 打开博客，发现锚图标功能正常，但是看不到锚图标

### 截图
![image](https://user-images.githubusercontent.com/38276635/78323802-949a9b00-7538-11ea-970a-21999797d83d.png)

**Comment by 0x2E** [comment]
注意缩进
```yml
anchorjs: # 为文章内容中的标题添加锚图标
  enable: true
  element: h1,h2,h3,h4,h5,h6
  placement: right # icon放置的位置： left | right
  visible: always # 默认悬浮显示，可选：hover（鼠标在元素上悬浮时显示） | always（一直显示） | touch（移动端触摸显示）
  icon: "§" # 可选：§ | # | ❡ 等，留空则为默认效果
```
