### ISSUE TITLE
希望增加设置表格背景色的选项。css中对.td 编辑无反应

### ISSUE THREAD

**Issue by crescenth** [fluid-dev/hexo-theme-fluid#260]
如题

**Comment by zkqiang** [comment]
```css
.markdown-body table tr {
  background-color: #000000
}

.markdown-body table tr:nth-child(2n) {
  background-color: #1f1f1f
}
```

无反应是因为css优先级
