### ISSUE TITLE
Katex公式渲染会重复

### ISSUE THREAD

**Issue by seineo** [fluid-dev/hexo-theme-fluid#295]
#### 请确认
- [Yes ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ Yes] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法
- 已更换为katex渲染器，配置如下：
```yml
post:
  math:
    enable: false
    specific: true
    engine: katex
```

#### 问题描述

katex在渲染后会跟着一个原来的公式文本（在typora上显示是没问题的）
具体显示如下；
![图片](https://user-images.githubusercontent.com/50976339/85359741-b1e47180-b549-11ea-8564-4841074db4c5.png)

请问是我哪里操作错误了吗？弄了很久没搞明白，希望大家可以帮助我，谢谢。
