### ISSUE TITLE
实在找不到首页背景图的配置项了，绝望

### ISSUE THREAD

**Issue by RexkentZheng** [fluid-dev/hexo-theme-fluid#441]
#### 请确认
- [ ✅] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ✅] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

看官方文档看了两个小时，就硬生生没找到首页背景图配置项，其他几乎所有配置项都看了，就是没看见首页背景图的配置项，尝试了一些配置项，可是没生效

```
// _config.fluid.yml
...
index:
  slogan:
    enable: true
    text: 这是一条 Slogan
    api:
      enable: true
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]
  banner_img: https://pic2.zhimg.com/v2-19cf8bf0a05a7f32b8a3ad8924f3ce15_540x450.jpeg
navbar:
  blog_title: Here is RZ
home:
  banner_img: https://pic2.zhimg.com/v2-19cf8bf0a05a7f32b8a3ad8924f3ce15_540x450.jpeg
banner_img: https://pic2.zhimg.com/v2-19cf8bf0a05a7f32b8a3ad8924f3ce15_540x450.jpeg
```

在index下面配置了banner_img，在home下又配置了，最后在跟节点又配置了，依然不生效，实在没办法了，求指教
