### ISSUE TITLE
问题求助

### ISSUE THREAD

**Issue by lxh20061128** [fluid-dev/hexo-theme-fluid#467]
更新到最新版本1.8.10以后为什么字体的修改失效了呢？
```
# 主题字体配置
# Font
font:
  font_size: 18px
  font_family: Muyao-Softbrush
  code_font_size: 85%
```
```
# 指定自定义 .css 文件路径，用法和 custom_js 相同
# The usage is the same as custom_js
custom_css:
  - //cdn.jsdelivr.net/gh/lxh20061128/image/project/font/Muyao-Softbrush.css #字体
```

**Comment by zkqiang** [comment]
![image](https://user-images.githubusercontent.com/32983588/116179955-ba4da000-a74a-11eb-8469-006068e241db.png)

我看是生效的，可能是缓存原因

**Comment by lxh20061128** [comment]
不是的，更新主题新版本我还没部署
本地打开服务看的
![Uploading](https://img.imgdb.cn/item/6087a3e5d1a9ae528f5cc956.png)

**Comment by lxh20061128** [comment]
> ![image](https://user-images.githubusercontent.com/32983588/116179955-ba4da000-a74a-11eb-8469-006068e241db.png)
> 
> 我看是生效的，可能是缓存原因

不是的，更新主题新版本我还没部署
本地打开服务看的
![](https://img.imgdb.cn/item/6087a3e5d1a9ae528f5cc956.png)

**Comment by zkqiang** [comment]
那你部一个看看，不然很难知道问题

**Comment by lxh20061128** [comment]
咋办？我部署了，还清除了缓存，等了一段时间，发现确实字体修改失效了

**Comment by zkqiang** [comment]
定位到问题了

你可以参照 https://github.com/fluid-dev/hexo-theme-fluid/commit/04ef1706be205410ef6ff8c8074620a969c4b7d6 修改

或者通过自定义 css 加入
```css
html, body {
    font-family: Muyao-Softbrush
}
```
