### ISSUE TITLE
highlightjs 代码高亮无法正常渲染缩进代码

### ISSUE THREAD

**Issue by fanlumaster** [fluid-dev/hexo-theme-fluid#494]
#### Bug 描述

我的问题是在代码高亮配置为 highlightjs 的 Atom One Dark 的情况下，关于采用 TAB 间缩进的代码无法正常渲染，效果如下

![](https://cdn.jsdelivr.net/gh/fanlumaster/BlogMaps@master/blogs/pictures/20210606220528.png)

主题配置文件中，代码高亮配置如下：

```yml
# 代码高亮
# Code highlight
highlight:
  enable: true

# 代码块是否显示行号
# If true, the code block display line numbers
line_number: true

# 实现高亮的库，对应下面的设置
# Highlight library
# Options: highlightjs | prismjs
lib: "highlightjs"

highlightjs:
  # 在链接中挑选 style 填入
  # Select a style in the link
  # See: https://highlightjs.org/static/demo/
  style: "Atom One Dark"

  # 是否根据 style 改变代码背景色（如果 style 是深色背景别忘了开启此项）
  # If true, the code background will change color based on the style (If style has a dark background, don't forget to true)
  bg_color: true

prismjs:
  # 在下方链接页面右侧的圆形按钮挑选 style 填入，也可以直接填入 css 链接
  # Select the style button on the right side of the link page, you can also set the CSS link
  # See: https://prismjs.com/
  style: "default"

  # 设为 true 高亮将本地静态生成（并只支持部分 prismjs 插件），设为 false 高亮将在浏览器通过 js 生成
  # If true, it will be generated locally (but some prismjs plugins are not supported). If false, it will be generated via JS in the browser
  preprocess: true
```
