### ISSUE TITLE
slogan颜色如何更改

### ISSUE THREAD

**Issue by bingheng-wlm** [fluid-dev/hexo-theme-fluid#532]
在更换了浅色的首页背景图后，slogan文字颜色仍是白色，找不到如何修改

**Comment by zkqiang** [comment]
自定义CSS

```css
#subtitle {
  color: #000000
}
```
