### ISSUE TITLE
分类页面，存在多级分类时展开工作不正常

### ISSUE THREAD

**Issue by tabris-trees** [fluid-dev/hexo-theme-fluid#535]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述
分类页面，除最后一级可以展开文章标题列表外（默认是未展开的状态），前几级分类默认展开，且无法收起，浏览器: Chrome

#### 复现步骤
该 Bug 复现步骤如下：
1. 文章中分类的方式：
```markdown
categories:
- [学习,笔记,编程,Fortran]
```
2. _config设置：
```yaml
#---------------------------
# 分类页
# Category Page
#---------------------------
category:
  enable: true
  banner_img: https://trees-1301133429.cos.ap-nanjing.myqcloud.com/blogweb/%E8%A1%97%E5%8F%A3.jpeg
  banner_img_height: 60
  banner_mask_alpha: 0.3
  subtitle: '平行宇宙的啦(*^▽^*)'

  # 分类的排序字段，前面带减号是倒序，不带减号是正序
  # Sort field for categories, with a minus sign is reverse order
  # Options: length | name
  order_by: "-length"

  # 层级的折叠深度，0 是全部折叠，大于 0 后如果存在子分类则默认展开
  # Collapse depth. If 0, all posts collapsed. If greater than 0, it will be expanded by default if there are subcategories
  collapse_depth: 0

  # 文章的排序字段，前面带减号是倒序，不带减号是正序
  # Sort field for posts, with a minus sign is reverse order
  # Options: date | title | or other field of front-matter
  post_order_by: "-date"

  # 单个分类中折叠展示文章数的最大值，超过限制会显示 More，0 则不限制
  # The maximum number of posts in a single category. If the limit is exceeded, it will be displayed More. If 0 no limit
  post_limit: 10
```
3. 在分类页面点击前几级分类的展开按钮
4. 没有反应

https://www.tabirstrees.top/categories/

#### 截图
![shili](https://user-images.githubusercontent.com/39879580/127938309-093cf50e-5f3c-4bb9-ab58-2f8239fc3a38.gif)
