### ISSUE TITLE
无法通过主题配置显示代码行号

### ISSUE THREAD

**Issue by hooyuser** [fluid-dev/hexo-theme-fluid#553]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述
无法通过主题配置显示代码行号

#### 复现步骤
fluid_config.yml 配置为
```
code:  # 代码块相关的配置
  copy_btn: true  # 是否开启复制代码的按钮
  highlight:  # 代码高亮
    enable: true
    line_number: true
    lib: 'highlightjs'  # 实现高亮的库，可选：highlightjs | prismjs，对应下面的配置项
    highlightjs:
      style: 'Androidstudio'  # 高亮样式见：https://highlightjs.org/static/demo/  在页面挑选 style 填入
      bg_color: true # 是否根据 style 改变代码背景色，**如果 style 是深色背景别忘了开启此项**
    prismjs:
      style: 'TOMORROW NIGHT'  # 高亮样式见：https://prismjs.com/  在页面右侧的圆形按钮挑选 style 填入，也可以直接填入 css 链接
      preprocess: false  # 设为 true 高亮将本地静态生成（并只支持部分 prismjs 插件），设为 false 高亮将在浏览器通过 js 生成
```
页面地址：
https://toposcat.top/cn/2021/04/27/Image-Based%20Lighting/#%E9%A2%84%E8%AE%A1%E7%AE%97%E8%BE%90%E7%85%A7%E5%BA%A6%E8%B4%B4%E5%9B%BE

#### 截图
![code](https://user-images.githubusercontent.com/10691820/129456885-a7c178ca-1510-4e42-923b-cd5d88173a50.png)
