### ISSUE TITLE
文章更新时间问题

### ISSUE THREAD

**Issue by Macr0phag3** [fluid-dev/hexo-theme-fluid#571]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
文章更新时间有点问题，已经在 `_config.yml` 中配置了:
```
...
  updated:
    enable: true

    # 描述文字
    # Descriptive text before date
    content: 本文最后更新于：

    # 是否使用相对时间表示，比如："3 天前"
    # If true, it will be a relative time, such as: "3 days ago"
    relative: true

...
```

但是文章中显示的更新时间是 .md 文件的创建时间而不是修改时间。

如果手动在 .md 中指定 `updated` 是可以正常显示的。
