### ISSUE TITLE
如何在自定义页面中使用弹出式图片浏览器

### ISSUE THREAD

**Issue by ragnaroks** [fluid-dev/hexo-theme-fluid#576]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
[比如这个页面](https://www.ragnaroks.site/pages/zerotier/)，希望点击图片可以弹出文章页那样的图片浏览器

**Comment by zkqiang** [comment]
https://github.com/fluid-dev/hexo-theme-fluid/blob/be2c78410d7daef3f6ac1685f8d8b735a332a79c/_config.yml#L580-L586

**Comment by ragnaroks** [comment]
不是这个问题，是**自定义页面**没有像**文章页**那样的图片放大，不是说**文章页**没有图片放大。

这里的配置没有改动过  /source/_data/fluid_config.yml  
```yml
#---------------------------
# 以下是配置 JS CSS 等静态资源的 URL 前缀，可以自定义成 CDN 地址，
# 默认的 jsDelivr CDN 可能在部分地区无法访问，如果需要修改，最好使用与默认配置相同的版本，以避免潜在的问题，
# ** 如果你不知道如何设置，请不要做任何改动 **
#
# Here is the url prefix to configure the static assets. Set CDN addresses you want to customize.
# Be aware that you would better use the same version as default ones to avoid potential problems.
# DO NOT EDIT THE FOLLOWING SETTINGS UNLESS YOU KNOW WHAT YOU ARE DOING
#---------------------------
static_prefix:
  anchor: /npm/anchor-js@4.3.1/
  github_markdown: /npm/github-markdown-css@4.0.0/
  jquery: /npm/jquery@3.6.0/dist/
  bootstrap: /npm/bootstrap@4.6.0/dist/
  highlightjs: /npm/highlight.js@10.7.2/
  prismjs: /npm/prismjs@1.23.0/
  tocbot: /npm/tocbot@4.12.2/dist/
  typed: /npm/typed.js@2.0.11/lib/
  fancybox: /npm/@fancyapps/fancybox@3.5.7/dist/
  nprogress: /npm/nprogress@0.2.0/
  clipboard: /npm/clipboard@2.0.8/dist/

# 一些好玩的功能
fun_features:
  # 为 subtitle 添加打字机效果
  typing:
    enable: false
  # 为文章内容中的标题添加锚图标
  anchorjs:
    # icon放置的位置： left | right
    placement: 'left'
    # 默认悬浮显示，可选：hover（鼠标在元素上悬浮时显示） | always（一直显示） | touch（移动端触摸显示）
    visible: 'always'
    # 可选：§ | # | ❡ 等，留空则为默认效果
    icon: '§'

# 页头
navbar:
  # 导航栏左侧的标题，为空则按 hexo config.title 显示
  blog_title:
  # 导航栏毛玻璃特效，实验性功能，可能会造成页面滚动掉帧和抖动，部分浏览器不支持会自动不生效
  ground_glass:
    enable: false
  # 可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
    - { key: '页面索引', link: '/pages/', icon: 'iconfont icon-list' }

# 单独页面
page:
  banner_img: /images/banner/default.png
  banner_img_height: 30
```
