### ISSUE TITLE
's 這幾個英文符號在網頁會變成‘ s，視覺上實際隔得更大

### ISSUE THREAD

**Issue by anthonyweidai** [fluid-dev/hexo-theme-fluid#583]
如題所示，對英文blogs有些不友好，希望能在新版優化一下。

**Comment by zkqiang** [comment]
![image](https://user-images.githubusercontent.com/32983588/134501599-a86f8355-98cf-4815-ad7a-d24edf720c4f.png)

有具体的示例和截图吗？在我这里显示还比较正常

**Comment by anthonyweidai** [comment]
原文：Recommender systems are powerful tools to effectively predict people's taste. Thus, it has huge business value for advertisers.
在typora，markdown編輯工具：
![image](https://user-images.githubusercontent.com/44538872/134505438-82543c1b-f500-4fa2-bb5b-b535c93537ea.png)
在網頁：
![image](https://user-images.githubusercontent.com/44538872/134505313-774a2db1-28b4-43f3-91c6-ee861261204f.png)

**Comment by anthonyweidai** [comment]
Website: https://anthonydave.top/Machine%20leanring/Recommender-Systems-Class-Review/

**Comment by zkqiang** [comment]
这应该是微软雅黑字体中的 `’` 本身就是如此，可以通过 `font_family` 自行指定字体去除微软雅黑

**Comment by zkqiang** [comment]
建议升级最新版本，新版本已经不包含 微软雅黑 字体了

**Comment by anthonyweidai** [comment]
我設置了font_family, 可以，thanks bro
```
font:
  font_size: 16px
  font_family: Verdana, Arial, Helvetica, sans-serif
  letter_spacing: 0.02em
  code_font_size: 85%
```
