### ISSUE TITLE
代码块的复制按钮在暗色模式下会固定到代码块内容的右端

### ISSUE THREAD

**Issue by KiyanYang** [fluid-dev/hexo-theme-fluid#624]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

代码块的复制按钮在暗色模式下会固定到代码块内容的右端，而不是代码块的右端，参考截图。

#### 复现步骤
该 Bug 复现步骤如下：
1. 在包含代码块的文章切换至暗色模式
2. 使代码块出现水平进度条（若代码每行较短，可以调整浏览器的宽度使其出现水平进度条）
3. 这时代码块的复制按钮在暗色模式下会固定到代码块内容的右端，而不是代码块的右端，参考截图。

复现地址：[我的博客](https://kiyanyang.github.io/)，[Fluid's blog](https://hexo.fluid-dev.com/) 等

#### 截图

-  图 1 右上无复制按钮

   <img width="458" alt="Snipaste_2021-12-12_17-17-12" src="https://user-images.githubusercontent.com/50903774/145706914-d9229996-6604-4bad-ab98-58cb14d78175.png">

- 图 2 （动图）演示内容：右上无复制按钮 -> 水平滚动条右移至接近最右侧开始出现复制按钮（不完整）-> 在最右侧出现正常的复制按钮 ->  水平滚动条左移至接近最右侧开始再次出现复制按钮（不完整）-> 返回最左侧，右上无复制按钮

  ![动画](https://user-images.githubusercontent.com/50903774/145706925-322e9296-c75d-4831-9223-9f621390b3f4.gif)

**Comment by zkqiang** [comment]
找到了原因（<https://www.cnblogs.com/Wayou/p/css_filter_issue.html>）

但是还没找到解决办法，先留存

**Comment by KiyanYang** [comment]
> 找到了原因（https://www.cnblogs.com/Wayou/p/css_filter_issue.html）
> 
> 但是还没找到解决办法，先留存

一个可能的解决方案，对代码块的 `table` 进行操作：
```css
[data-user-color-scheme="dark"] figure.highlight table {
  -webkit-filter: brightness(0.9);
  filter: brightness(0.9);
  transition: filter 0.2s ease-in-out;
}

/* 对应 css/_pages/_base/color-schema.styl */
[data-user-color-scheme="dark"] .markdown-body pre,
[data-user-color-scheme="dark"] .markdown-body td.gutter,
[data-user-color-scheme="dark"] .markdown-body td.code > .code-wrapper {
  -webkit-filter: unset;
  filter: unset;
  transition: unset;
}
```
