### ISSUE TITLE
:warning: 解决样式加载失败（更换 CDN 配置）

### ISSUE THREAD

**Issue by zkqiang** [fluid-dev/hexo-theme-fluid#656]
国内部分网络的 jsDelivrCDN 会无法连通，可以在主题配置的最底部，替换为如下配置（注意使用[覆盖配置](https://hexo.fluid-dev.com/docs/guide/#%E8%A6%86%E7%9B%96%E9%85%8D%E7%BD%AE)）：

```yaml
static_prefix:
  # 内部静态
  # Internal static
  internal_js: /js
  internal_css: /css
  internal_img: /img

  anchor: https://lib.baomitu.com/anchor-js/4.3.1/

  github_markdown: https://lib.baomitu.com/github-markdown-css/4.0.0/

  jquery: https://lib.baomitu.com/jquery/3.6.0/

  bootstrap: https://lib.baomitu.com/twitter-bootstrap/4.6.1/

  prismjs: https://lib.baomitu.com/prism/1.26.0/

  tocbot: https://lib.baomitu.com/tocbot/4.18.0/

  typed: https://lib.baomitu.com/typed.js/2.0.12/

  fancybox: https://lib.baomitu.com/fancybox/3.5.7/

  nprogress: https://lib.baomitu.com/nprogress/0.2.0/

  mathjax: https://lib.baomitu.com/mathjax/3.2.0/

  katex: https://lib.baomitu.com/KaTeX/0.15.2/

  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/

  clipboard: https://lib.baomitu.com/clipboard.js/2.0.10/

  mermaid: https://lib.baomitu.com/mermaid/8.13.10/

  valine: https://lib.baomitu.com/valine/1.4.16/

  waline: https://lib.baomitu.com/waline/1.5.2/

  gitalk: https://lib.baomitu.com/gitalk/1.7.2/

  disqusjs: https://lib.baomitu.com/disqusjs/1.3.0/

  twikoo: https://lib.baomitu.com/twikoo/1.4.17/

  hint: https://lib.baomitu.com/hint.css/2.7.0/
```
