### ISSUE TITLE
文章中的图片是否可以关闭圆角和阴影

### ISSUE THREAD

**Issue by hyoban** [fluid-dev/hexo-theme-fluid#674]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

文章中的图片是否可以关闭圆角和阴影，mac 截图自带阴影的话就会有双重阴影了

**Comment by hyoban** [comment]
未找到配置选项，自定义 css 方式如下，供他人参考

```css
.markdown-body p > img,
.markdown-body p > a > img {
  box-shadow: unset;
  border-radius: 0px;
}
```
