### ISSUE TITLE
language 配置不生效

### ISSUE THREAD

**Issue by cool-cold** [fluid-dev/hexo-theme-fluid#680]
# 版本：
- hexo: 5.4.1
- fluid: ^1.8.14

# fluid 安装方式
```shell
npm install --save hexo-theme-fluid
```

# 语言配置文件放置目录
```
source/_data/languages/zh-CN.yml
```

# `zh-CN.yml`文件内容
```shell
search:
  title: 搜索
  keyword: 关键词
  status:
    success: v
    error: x

postTotal: 共计 %d 篇文章

paginator:
  pre: 上一页
  next: 下一页

post:
  toc: 目录
  pre: 上一篇
  next: 下一篇

home:
  title: 首页

archive:
  title: 归档
  subtitle: 归档

tag:
  title: 标签
  subtitle: 标签

category:
  title: 分类
  subtitle: 分类

about:
  title: 关于
  subtitle: 关于

page404:
  title: 页面走丢啦~
  subtitle: 页面走丢啦~

tools:
  title: 工具
  subtitle: 工具

links:
  title: 友链
  subtitle: 友情链接

```

# 菜单配置
```yaml
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - {
        key: "category",
        link: "/categories/",
        icon: "iconfont icon-category-fill",
      }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "tools", link: "/tools/", icon: "iconfont icon-briefcase" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }
```

# 预期
菜单栏`tools`翻译为 ***工具***

# 实际输出
![WechatIMG44 (1)](https://user-images.githubusercontent.com/31332480/158044071-e08036a9-b560-43ac-8534-660a9cc5d7fa.png)
