### ISSUE TITLE
更改导航栏文字颜色后，点击搜索功能后退出，图标颜色变为白色而非修改后的文字颜色

### ISSUE THREAD

**Issue by OrdChaos** [fluid-dev/hexo-theme-fluid#687]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 浏览器不属于 IE 等非主流浏览器 
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述

更改导航栏文字颜色后，点击搜索功能后退出，图标颜色变为白色而非修改后的文字颜色，需要点击一下任意地方才可以恢复。浏览器: chrome.

#### Config相关设置
```
# 主题颜色配置，其他不生效的地方请使用自定义 css 解决，配色可以在下方链接中获得启发
# Theme color, please use custom CSS to solve other colors, color schema can be inspired by the links below
# See: https://www.webdesignrankings.com/resources/lolcolors/
color:
  # body 背景色
  # Color of body background
  body_bg_color: "#fff"
  # 暗色模式下的 body 背景色，下同
  # Color in dark mode, the same below
  body_bg_color_dark: "#181c27"

  # 顶部菜单背景色
  # Color of navigation bar background
  navbar_bg_color: "#ffffff"
  navbar_bg_color_dark: "#1f3144"

  # 顶部菜单字体色
  # Color of navigation bar text
  navbar_text_color: "#3c4858"
  navbar_text_color_dark: "#d0d0d0"

  # 全局字体色
  # Color of global text
  text_color: "#3c4858"
  text_color_dark: "#c4c6c9"

  # 全局次级字体色（摘要、简介等位置）
  # Color of global secondary text (excerpt, introduction, etc.)
  sec_text_color: "#718096"
  sec_text_color_dark: "#a7a9ad"

  # 文章正文字体色
  # Color of post text
  post_text_color: "#2c3e50"
  post_text_color_dark: "#c4c6c9"

  # 文章正文字体色（h1 h2 h3...）
  # Color of Article heading (h1 h2 h3...)
  post_heading_color: "#1a202c"
  post_heading_color_dark: "#c4c6c9"

  # 文章超链接字体色
  # Color of post link
  post_link_color: "#0366d6"
  post_link_color_dark: "#1589e9"

  # 超链接悬浮时字体色
  # Color of link when hovering
  link_hover_color: "#30a9de"
  link_hover_color_dark: "#30a9de"

  # 超链接悬浮背景色
  # Color of link background when hovering
  link_hover_bg_color: "#f8f9fa"
  link_hover_bg_color_dark: "#364151"

  # 主面板背景色
  # Color of main board
  board_color: "#fff"
  board_color_dark: "#252d38"

  # 滚动条颜色
  # Color of scrollbar
  scrollbar_color: "#3c4858"
  scrollbar_color_dark: "#687582"
  scrollbar_hover_color: "#a6a6a6"
  scrollbar_hover_color_dark: "#9da8b3"
```

#### 复现步骤
该 Bug 复现步骤如下：
1. (在config中修改导航栏文字颜色)
2. 在任意页面点击搜索按钮
3. 退出搜索界面
4. 图标颜色变白，点击一下任意地方恢复。
5. 可复现的地址：我的博客 https://www.ordchaos.com

#### 截图
![image](https://user-images.githubusercontent.com/101442840/159151428-88375a84-0e98-4489-9d64-836c35830112.png)
![image](https://user-images.githubusercontent.com/101442840/159151441-fcf9d90e-38db-4d2d-ad6e-c8cf8b3c670a.png)
![image](https://user-images.githubusercontent.com/101442840/159151451-c5e76ea1-087e-4183-a276-5f009b6a4608.png)
