### ISSUE TITLE
部署到github后，文章更新时间不变，一直是几秒前

### ISSUE THREAD

**Issue by leon0625** [fluid-dev/hexo-theme-fluid#699]
fluid更新时间的配置如下，显示相对时间
```
  updated:
    enable: true

    # 描述文字
    # Descriptive text before date
    content: 本文最后更新于：

    # 是否使用相对时间表示，比如："3 天前"
    # If true, it will be a relative time, such as: "3 days ago"
    relative: true

````
文章内容开头如下：
```
---
title: 博客使用
date: 2022-4-4 11:41:12
updated: 2022-04-05 22:26:37
postHexo: true

---
```
但是在github.io上看到时间一直是几秒钟前
![image](https://user-images.githubusercontent.com/20039046/161777865-16fac728-fccb-4edd-8da2-9280cff5f27d.png)

`hexo s`起本地服务进localhost:4000浏览，是没有问题，时间会一直变化

请问这个问题怎么排查呀
