### ISSUE TITLE
添加自定义页面失败

### ISSUE THREAD

**Issue by 2w1nd** [fluid-dev/hexo-theme-fluid#708]
#### 请确认
- [ ] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [ ] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

我想添加一个读书页，使用`hexo new page book`，然后在`config.yml`配置了以下代码，但没有生效
```
#---------------------------
# 读书页
# Book Page
#---------------------------
book:
  enable: true
  banner_img: /img/Default5.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3
```
