### ISSUE TITLE
about 页面 banner avatar 等内容无法正确生成

### ISSUE THREAD

**Issue by Surmiloo** [fluid-dev/hexo-theme-fluid#733]
# 我的版本

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.2.0"
  },
  "dependencies": {
    "hexo": "^6.2.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^5.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-fluid": "^1.8.14",
    "hexo-theme-landscape": "^0.0.3"
  }
}
```
# 我的about页面配置

```yml
about:
  enable: true
  banner_img: /img/aboutme.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3
  subtitle: abcd
  avatar: /img/touxiang1.jpg
  name: "abc"
  intro: "abcdefg"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-gitlab-fill", link: "*******", tip: "GitLab" }
    # - { class: "iconfont icon-bilibili", link: "https://space.bilibili.com/9135331?spm_id_from=333.1007.0.0", tip: "bilibili" }
    # - { class: "iconfont icon-github-fill", link: "https://github.com", tip: "GitHub" }
    # - { class: "iconfont icon-douban-fill", link: "https://douban.com", tip: "豆瓣" }
    # - { class: "iconfont icon-wechat-fill", qrcode: "/img/favicon.png" }
```

# about 页面内容

```md
---
title: 关于
date: 2022-05-16 00:30:16
---

# 欢迎来到 abc 的博客

# 1
1
1
1
# 1
1
1
1
```

![2022-05-16_09-41](https://user-images.githubusercontent.com/31952942/168506161-849d7ba0-71ff-438c-9062-4fa85f927439.png)
