### ISSUE TITLE
首页蒙版透明度设置为 0 无效

### ISSUE THREAD

**Issue by mofankk** [fluid-dev/hexo-theme-fluid#741]
#### Bug 描述
首页配置中，蒙版透明度设置为0时的效果以及配置与描述信息不太一致：
1. 设置为 0 时效果和默认的 0.3 透明度一致；
2. 完全透明需要设置为 一个负值，比如 -1
见下方代码配置项：index.banner_mask_alpha
```
  #---------------------------
  # 首页
  # Home Page
  #---------------------------
  index:
    # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
    # Path of Banner image, can be a relative path or an absolute path, the same   on other pages
    banner_img: /img/default.png
  
    # 头图高度，屏幕百分比
    # Height ratio of banner image
    # Available: 0 - 100
    banner_img_height: 100
  
    # 头图黑色蒙版的不透明度，available: 0 - 1.0， 1 是完全不透明
    # Opacity of the banner mask, 1.0 is completely opaque
    # Available: 0 - 1.0
    banner_mask_alpha: 0
```

#### 复现步骤
该 Bug 复现步骤如下：
假定目前首页 index.banner_mask_alpha 为 0.3，
1. 设置首页 index.banner_mask_alpha 为 0 后，刷新页面，发现效果不变；
3. 设置为 0.1 透明度变高，即 0.1 的 透明度比 0 的透明度高；
4. 使用 1.8 版本，在两个版本都是 0 的情况下，1.8 的透明度比 1.9 版本的高
5. 都是 1.9 版本情况下，设置为 -1 比 设置为 0 透明度高（貌似可以理解为完全透明）
