### ISSUE TITLE
Abnormal display of left menu

### ISSUE THREAD

**Issue by kissycn** [fluid-dev/hexo-theme-fluid#780]
#### Make sure
- [x] Upgrade the latest [release](https://github.com/fluid-dev/hexo-theme-fluid/releases).
- [x] Browser does not belong to IE and other old browsers
- [x] It can be replicated through `hexo clean && hexo s` and cleared browser cache in the localhost.
- [x] Not affected by other Hexo plugins

#### Describe the bug

The category menu of the article details page is displayed repeatedly
<img width="267" alt="image" src="https://user-images.githubusercontent.com/89451328/174945665-2b948b69-b7c2-440a-851f-d4a404a1563d.png">

#### To Reproduce
The category menu of the article details page is displayed repeatedly
current fluid version is 1.9.2 and _config.yaml param like this:
```yaml
...
  # 侧边栏展示当前分类下的文章
  # Sidebar of category
  category_bar:
    enable: true

    # 开启后，只有在文章 Front-matter 里指定 `category_bar: true` 才会展示分类，也可以通过 `category_bar: ["分类A"]` 来指定分类
    # If true, only set `category_bar: true` in Front-matter will enable sidebar of category, also set `category_bar: ["CategoryA"]` to specify categories
    specific: true

    # 置于板块的左侧或右侧
    # place in the board
    # Options: left | right
    placement: left

    # 文章的排序字段，前面带减号是倒序，不带减号是正序
    # Sort field for posts, with a minus sign is reverse order
    # Options: date | title | or other field of front-matter
    post_order_by: "date"

    # 单个分类中折叠展示文章数的最大值，超过限制会显示 More，0 则不限制
    # The maximum number of posts in a single category. If the limit is exceeded, it will be displayed More. If 0 no limit
    post_limit: 3
...
```
The MD file YAML FrontMatter  configuration of the article page is as follows：
``` yaml
categories:
  - go
  - 读书笔记
category_bar: true
```
According to the menu configuration specification, I configured two-level menus, but the second level menu is always displayed repeatedly
