### ISSUE TITLE
子数统计 wordcount 不生效显示 undefined

### ISSUE THREAD

**Issue by idelin** [fluid-dev/hexo-theme-fluid#822]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

怎么字数统计 wordcount 不生效，配置有什么问题吗，显示undefined
![image](https://user-images.githubusercontent.com/23070481/186126527-f7fec885-d0e9-4ffb-97ec-51e877ac7178.png)

**Comment by idelin** [comment]
# 字数统计
    # Word count
    wordcount:
      enable: true

    # 估计阅读全文需要的时长
    # Estimated reading time
    min2read:
      enable: true
      # 每个字词的长度，建议：中文≈2，英文≈5，中英混合可自行调节
      # Average word length (chars count in word), ZH ≈ 2, EN ≈ 5
      awl: 2
      # 每分钟阅读字数，如果大部分是技术文章可适度调低
      # Words per minute
      wpm: 60

**Comment by idelin** [comment]
相关配置
```
  # 字数统计
    # Word count
    wordcount:
      enable: true

    # 估计阅读全文需要的时长
    # Estimated reading time
    min2read:
      enable: true
      # 每个字词的长度，建议：中文≈2，英文≈5，中英混合可自行调节
      # Average word length (chars count in word), ZH ≈ 2, EN ≈ 5
      awl: 2
      # 每分钟阅读字数，如果大部分是技术文章可适度调低
      # Words per minute
      wpm: 60
```
