### ISSUE TITLE
文章置顶功能无效

### ISSUE THREAD

**Issue by li-zheng-hao** [fluid-dev/hexo-theme-fluid#836]
已安装的包：
![image](https://user-images.githubusercontent.com/22129824/190850258-c809e81c-a921-4624-9f52-acf2b29b39f5.png)

文章配置：
```
---
title: XXXX
sticky: 10
---
```

fluid配置：
```
# 文章通过 sticky 排序后，在首页文章标题前显示图标
# If the posts are sorted by `sticky`, an icon is displayed in front of the post title
post_sticky:
  enable: true
  icon: "iconfont icon-top"
```
