### ISSUE TITLE
请问如何修改行内代码的颜色

### ISSUE THREAD

**Issue by LingkKang** [fluid-dev/hexo-theme-fluid#862]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述

想要修改行内代码块的颜色，尝试在启用 `custom_css` 后并加入如下代码，

``` css

code {
    color: rgb(56 160 110);
}

.markdown-body code {
    color: rgb(56 160 110);
}

```

但是代码块中的非关键字内容也被一并修改了颜色（如下图）。

![image](https://user-images.githubusercontent.com/104191582/198528820-231d07e5-e0e9-4685-8317-7ee0bca1a118.png)

请问如何只修改行内代码的颜色，并且保持代码块中的非关键字颜色保持正常？

先谢谢啦。
