### ISSUE TITLE
Support mathjax `Automatic Equation Numbering`

### ISSUE THREAD

**Issue by Zhaopudark** [fluid-dev/hexo-theme-fluid#879]
#### 如是功能需求，请确定符合以下情况
- [ ] 难以通过[自定义](https://hexo.fluid-dev.com/docs/guide/#自定义-js-css-html)实现
- [ ] 难以通过第三方插件实现

#### 请描述该需求尝试解决的问题

How to configure mathjax to enable [automatic equation numbering](https://docs.mathjax.org/en/latest/input/tex/eqnumbers.html#automatic-equation-numbering)?
If using the theme `NEXT`,  the automatic equation numbering can be realized as:

```yaml
mathjax:
    enable: false
    # Available values: none | ams | all
     tags: all
```
But when using `fluid`, it seems do not work, regardless of any the following syntax:

```yaml
mathjax:
  tex: 
    tags: 'all'
  tags: 'all'
math: 
  mathjax:
    tex: 
      tags: 'all'
    tags: 'all'
  tags: 'all'  
```
So, does not `fluid` not support automatic equation numbering with mathjax recently? 

Look forward to this feature. Thanks in advance.
#### 请描述您认为可行的解决方案

Use a simple configuration to enable automatic equation numbering, such as:
```yaml
math: 
  mathjax:
    tex: 
      tags: 'all'
```
