### ISSUE TITLE
为什么gitalk不能部署到主题上QAQ

### ISSUE THREAD

**Issue by ncwzdlsd** [fluid-dev/hexo-theme-fluid#888]
```
comments:
    enable: true
    # 指定的插件，需要同时设置对应插件的必要参数
    # The specified plugin needs to set the necessary parameters at the same time
    # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis | giscus
    type: gitalk
    gitalk:
    github_id: ncwzdlsd
    repository: 
    client_id: 
    client_secret: 
```
已进行如上配置并下载gitalk插件
