### ISSUE TITLE
关于时间轴

### ISSUE THREAD

**Issue by ncwzdlsd** [fluid-dev/hexo-theme-fluid#903]
建议在归档界面优化一下时间轴，最好能实现单页显示全部文章，要不文章写多了想在归档中查看比较麻烦

**Comment by wanglh03** [comment]
同求，归档archives页面显示太少，希望不要分页

**Comment by AimTao** [comment]
@ncwzdlsd @wanglh03 在 _conf.yml 文件中修改 `per_page` 属性就可以了。

```yml
# Pagination
## Set per_page to 0 to disable pagination
per_page: 20  # 每页展示的数量
pagination_dir: page
```

ps：是 hexo 的 _conf.yml 文件，不是主题的 _config.fluid.yml 文件。
