### ISSUE TITLE
导航栏菜单设置了二级标题则一级标题的link失效。

### ISSUE THREAD

**Issue by 1515biubiubiu** [fluid-dev/hexo-theme-fluid#938]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 在 [用户指南](https://hexo.fluid-dev.com/docs/) 中没有找到解决办法

#### 问题描述
导航栏菜单设置了二级标题则一级标题的link失效。
```yaml

  # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
  # Navigation bar menu. `key` is used to associate languages/*.yml. If there is no association, the value of `key` itself will be displayed; if `icon` is a css class, it can be omitted; adding `name` can force the display of the specified name
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill",
        submenu: [
          { key: 'Spring Framework', link: '/categories/Spring-Framework'},
          { key: 'Spring Boot', link: '/categories/Spring-Boot' }
        ] }

```
key: "category"的link被设置为href="javascript:;"，请问这个应该怎么配置，使一级标题的link生效。
