### ISSUE TITLE
Fluid开启评论后，评论页面不显示

### ISSUE THREAD

**Issue by jinguoguang** [fluid-dev/hexo-theme-fluid#949]
请问一下开启评论插件后，评论界面只在友链页显示，如何显示在全部页面
hexo版本：5.0.0

```
comments:
    enable: true
    # 指定的插件，需要同时设置对应插件的必要参数
    # The specified plugin needs to set the necessary parameters at the same time
    # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis | giscus
    type: valine
```
