### ISSUE TITLE
日间模式的按钮文字可添加反白配置项吗？

### ISSUE THREAD

**Issue by huaxianyan** [fluid-dev/hexo-theme-fluid#974]
之前按钮没有添加 color 自定义配置的时候一直用的默认的，感觉还不错

但是自从出了可配置之后用起来总觉得哪里怪怪的，后来发现是日间模式按钮背景无论选择什么颜色文字都是黑色的原因导致的

是否可以考虑新增反白配置项，或者是按钮文字的颜色配置项？

**Comment by zkqiang** [comment]
可以自定义CSS修改：
```css
.markdown-body a.btn {
  color: #ddd;
}
```

不是很想增加单独的配置项，目前配置项太多了
