### ISSUE TITLE
移动端无摘要原位置仍然空白

### ISSUE THREAD

**Issue by hunshcn** [fluid-dev/hexo-theme-fluid#991]
#### 请确认
- [x] 是当前最新的 [Release 版本](https://github.com/fluid-dev/hexo-theme-fluid/releases)
- [x] 本地 `hexo clean && hexo s`，并且清除浏览器缓存，仍可复现
- [x] 已经排除是其他 Hexo 插件影响

#### Bug 描述
移动端无摘要原位置仍然空白

#### 复现步骤
该 Bug 复现步骤如下：
1. `_config.yaml` 关闭自动摘要
```yaml
  # 自动截取文章摘要
  # Auto extract post
  auto_excerpt:
    enable: false
```
2. 切换到移动端
![image](https://github.com/fluid-dev/hexo-theme-fluid/assets/11679819/458bd8af-8e14-4b5a-b86e-4301b47f7836)

https://hunsh.net/

https://github.com/fluid-dev/hexo-theme-fluid/issues/746
这个 issue 修复不全
